### ISSUE TITLE
Stop depending on external libraries

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-telemetry#32]
### Describe the Enhancement:
We want to start using this gem across our whole Ruby ecosystem. The `http` 4.x gem started including native extensions to parse http responses faster, but that makes building more fragile. For a low level library gem like this lets get rid of as many external dependencies as possible.

### Describe the Need:
Switch to a std http library, and any other libraries possible.

**Comment by clintoncwolfe** [comment]
The remaining dependencies aside from HTTP are:
 * ffi-yajl, a Chef-written interface to a C-based JSON library. We could probably do without this, but it is low risk since we own it. If there was one to trim this would be it.
 * concurrent-ruby, a threading library. Very useful for our use case, and it promises to be pure ruby and have no dependencies.
 * chef-config, needed for determining location to place telemetry files, and maintained by Chef.

**Comment by tas50** [comment]
@clintoncwolfe  I don't see where we actually require ffi-yajl. It looks like we're just using the standard JSON lib. Can we remove ffi-yajl?

**Comment by clintoncwolfe** [comment]
I see `ffi-yajl` as a gemspec dep but I also don't see it being required. I think it can be removed.

**Comment by tas50** [comment]
PR cut
